<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
        <PackageReference Include="Microsoft.ApplicationInsights" Version="2.22.0" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.24.0" />
        <!-- Azure Key Vault packages -->
        <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.*" />
        <PackageReference Include="Azure.Identity" Version="1.*" />
        <!-- Markdown processing -->
        <PackageReference Include="Markdig" Version="0.37.0" />
    </ItemGroup>
</Project>