name: Deploy DotNet project to Azure Function App

on:
  push:
    branches: ["develop", "test", "master"]

env:
  AZURE_FUNCTIONAPP_NAME: az-tw-website-${{ github.ref_name == 'master' && 'production' || github.ref_name }}
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './output'
  X_API_ENVIRONMENT_KEY: ${{ secrets.X_API_ENVIRONMENT_KEY }}
  USE_MOCK_STORAGE: ${{ secrets.USE_MOCK_STORAGE }}
  DOTNET_VERSION: '8.0.x'                   

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # For Linux, use ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
    # Print out the environment we're deploying to'
    - name: Print Deployment Target
      run: 'echo "🔁 Deploying to environment: ${{ github.ref_name }}"'
      
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    # Using Azure Credentials RBAC, so commented out lines 41-44
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # set up AZURE_RBAC_CREDENTIALS secrets in your repository

    - name: 'Inject Function App Settings'
      run: |
        az functionapp config appsettings set \
          --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
          --resource-group az-tw-website-functions \
          --settings X_API_ENVIRONMENT_KEY="${{ env.X_API_ENVIRONMENT_KEY }}" \
                      USE_MOCK_STORAGE="${{ env.USE_MOCK_STORAGE }}"

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Build the Function App'
      run: dotnet build --configuration Release --output ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

    - name: Generate robots.txt for mock environments
      if: contains(env.USE_MOCK_STORAGE, 'true')
      run: |
        # Create a robots.txt file to disallow all web crawlers
        echo "Generating robots.txt for mock environment"
        echo -e "User-agent: *\nDisallow: /" > ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/robots.txt

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
